name: Documentation Issue
description: File a report for a documentation issue.
title: "[Documentation Issue]: "
labels: ["doc-bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your dedication to Windows Server documentation!
  - type: textarea
    id: documentation-issue
    attributes:
      label: Documentation issue
      description: Please decribe in detail the problems with this document and what editing needs to be done.
      placeholder: Document issue
      value: "Describe the issue with the document."
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Windows Server are you running?
      options:
        - Windows Server 2012
        - Windows Server 2016
        - Windows Server 2019
        - Windows Server 2022
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
